# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Build stage
FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN go build -o mcp-weather main.go

# Final image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/mcp-weather .
ENV OWM_API_KEY=""

ENTRYPOINT ["./mcp-weather"]
